/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package winecatalog.frames;
import helpers.DatabaseConnect;
import helpers.TableModel;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import winecatalog.object.FilterObject;
import winecatalog.object.WineObject;

/**
 *
 * @author wans8
 */
public class HomeFrame extends javax.swing.JFrame {

    public Color clicked = new Color(201, 51, 58, 255);
    public Color stock = new Color(176, 0, 29, 255);
    public int menuItem = 0; 
    WineObject obj = new WineObject();
    public List<WineObject> shoppingCart = new ArrayList<>();
    public List<WineObject> wineList = new ArrayList<>();
    public DatabaseConnect db = new DatabaseConnect();
     /** Creates new form HomeFrame */
    
    
    public HomeFrame() {
        initComponents();
        customInit();
        }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basic = new javax.swing.JPanel();
        sidemenu = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        all_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        red_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        white_panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rose_panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filter_panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        shamp_panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tablepanel = new javax.swing.JPanel();
        headpanel = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        head_title = new javax.swing.JLabel();
        cbType = new javax.swing.JComboBox<>();
        cbSugar = new javax.swing.JComboBox<>();
        cbGrape = new javax.swing.JComboBox<>();
        cbCountry = new javax.swing.JComboBox<>();
        searchIcon = new javax.swing.JLabel();
        addDb = new javax.swing.JLabel();
        shopingCart = new javax.swing.JLabel();
        cartCount = new javax.swing.JLabel();
        clearCart = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        basic.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        basic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidemenu.setBackground(new java.awt.Color(176, 0, 29));
        sidemenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_focus(evt);
            }
        });
        sidemenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        head.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/head2.png"))); // NOI18N
        sidemenu.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        all_panel.setBackground(new java.awt.Color(176, 0, 29));
        all_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                all_panelMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Menu_24px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Все");

        javax.swing.GroupLayout all_panelLayout = new javax.swing.GroupLayout(all_panel);
        all_panel.setLayout(all_panelLayout);
        all_panelLayout.setHorizontalGroup(
            all_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_panelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        all_panelLayout.setVerticalGroup(
            all_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidemenu.add(all_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 360, 80));

        red_panel.setBackground(new java.awt.Color(176, 0, 29));
        red_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                red_panelMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Bar_24px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Красное вино");

        javax.swing.GroupLayout red_panelLayout = new javax.swing.GroupLayout(red_panel);
        red_panel.setLayout(red_panelLayout);
        red_panelLayout.setHorizontalGroup(
            red_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(red_panelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        red_panelLayout.setVerticalGroup(
            red_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidemenu.add(red_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 360, 80));

        white_panel.setBackground(new java.awt.Color(176, 0, 29));
        white_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                white_panelMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_White_Wine_24px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Белое вино");

        javax.swing.GroupLayout white_panelLayout = new javax.swing.GroupLayout(white_panel);
        white_panel.setLayout(white_panelLayout);
        white_panelLayout.setHorizontalGroup(
            white_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(white_panelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        white_panelLayout.setVerticalGroup(
            white_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidemenu.add(white_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 360, 80));

        rose_panel.setBackground(new java.awt.Color(176, 0, 29));
        rose_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rose_panelMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Wine_Glass_24px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Розовое вино");

        javax.swing.GroupLayout rose_panelLayout = new javax.swing.GroupLayout(rose_panel);
        rose_panel.setLayout(rose_panelLayout);
        rose_panelLayout.setHorizontalGroup(
            rose_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rose_panelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        rose_panelLayout.setVerticalGroup(
            rose_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidemenu.add(rose_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 360, 80));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Designed&Developed by ArtyomV");
        sidemenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, -1, 20));

        filter_panel.setBackground(new java.awt.Color(176, 0, 29));
        filter_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filter_panelMouseClicked(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Search_24px_1.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Фильтр");

        javax.swing.GroupLayout filter_panelLayout = new javax.swing.GroupLayout(filter_panel);
        filter_panel.setLayout(filter_panelLayout);
        filter_panelLayout.setHorizontalGroup(
            filter_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filter_panelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        filter_panelLayout.setVerticalGroup(
            filter_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidemenu.add(filter_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 360, 80));

        shamp_panel.setBackground(new java.awt.Color(176, 0, 29));
        shamp_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shamp_panelMouseClicked(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Champagne_24px.png"))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Игристое вино");

        javax.swing.GroupLayout shamp_panelLayout = new javax.swing.GroupLayout(shamp_panel);
        shamp_panel.setLayout(shamp_panelLayout);
        shamp_panelLayout.setHorizontalGroup(
            shamp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shamp_panelLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        shamp_panelLayout.setVerticalGroup(
            shamp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidemenu.add(shamp_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 360, 80));

        basic.add(sidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 710));

        tablepanel.setBackground(new java.awt.Color(255, 255, 255));
        tablepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headpanel.setBackground(new java.awt.Color(176, 0, 29));
        headpanel.setEnabled(false);
        headpanel.setPreferredSize(new java.awt.Dimension(750, 190));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_24px.png"))); // NOI18N
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        head_title.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        head_title.setForeground(new java.awt.Color(255, 255, 255));
        head_title.setText("Каталог");

        cbType.setAutoscrolls(true);

        searchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Search_24px_1.png"))); // NOI18N
        searchIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchIconMouseClicked(evt);
            }
        });

        addDb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Add_Database_24px_1.png"))); // NOI18N
        addDb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDbMouseClicked(evt);
            }
        });

        shopingCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Shopping_Cart_24px.png"))); // NOI18N
        shopingCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopingCartMouseClicked(evt);
            }
        });

        cartCount.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cartCount.setForeground(new java.awt.Color(255, 255, 255));
        cartCount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        clearCart.setBackground(new java.awt.Color(236, 90, 81));
        clearCart.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        clearCart.setForeground(new java.awt.Color(255, 255, 255));
        clearCart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clearCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Clear_Shopping_Cart_24px.png"))); // NOI18N
        clearCart.setText("Очистить корзину");
        clearCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearCartMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headpanelLayout = new javax.swing.GroupLayout(headpanel);
        headpanel.setLayout(headpanelLayout);
        headpanelLayout.setHorizontalGroup(
            headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headpanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headpanelLayout.createSequentialGroup()
                        .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbGrape, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(headpanelLayout.createSequentialGroup()
                        .addComponent(head_title, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearCart)))
                .addContainerGap())
            .addGroup(headpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cartCount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shopingCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headpanelLayout.createSequentialGroup()
                        .addComponent(addDb, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headpanelLayout.createSequentialGroup()
                        .addComponent(exit)
                        .addContainerGap())))
        );
        headpanelLayout.setVerticalGroup(
            headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cartCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shopingCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(head_title, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearCart))
                .addGap(9, 9, 9)
                .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbGrape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablepanel.add(headpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        catTable.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        catTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        catTable.setToolTipText("");
        catTable.setFillsViewportHeight(true);
        catTable.setGridColor(new java.awt.Color(255, 255, 255));
        catTable.setRowHeight(22);
        catTable.setSelectionBackground(new java.awt.Color(250, 0, 42));
        catTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(catTable);

        tablepanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 730, 500));

        basic.add(tablepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 750, 710));

        getContentPane().add(basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customInit() {    
        jScrollPane1.setVisible(false);
        catTable.setVisible(false);
        cbType.setVisible(false);
        cbSugar.setVisible(false);
        cbGrape.setVisible(false);
        cbCountry.setVisible(false);
        searchIcon.setVisible(false);
        clearCart.setVisible(false);
    }

    public void getList(String category) {
        boolean dbFl = false;
        dbFl = db.dbConnect();
        if (dbFl) {
            try {
                wineList = db.dbSelect(category);
                System.out.println(wineList.size());
            } catch (SQLException ex) {
                Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        TableModel tModel = new TableModel(wineList.size(), 6, wineList);
        catTable.setModel(tModel);
    }
    
    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void menu_focus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_focus
        // TODO add your handling code here:
        skipSelection(0, "Каталог");            
    }//GEN-LAST:event_menu_focus

    private void red_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_red_panelMouseClicked
        // TODO add your handling code here:
        skipSelection(1, "Красное вино");
        getList("Красное");
        red_panel.setBackground(clicked);     
    }//GEN-LAST:event_red_panelMouseClicked

    private void white_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_white_panelMouseClicked
        // TODO add your handling code here:
        skipSelection(2, "Белое вино");
        getList("Белое");
        white_panel.setBackground(clicked);
    }//GEN-LAST:event_white_panelMouseClicked

    private void rose_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rose_panelMouseClicked
        // TODO add your handling code here:
        skipSelection(3, "Розовое вино");
        getList("Розовое");
        rose_panel.setBackground(clicked);      
    }//GEN-LAST:event_rose_panelMouseClicked

    private void all_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_all_panelMouseClicked
        // TODO add your handling code here:
        skipSelection(5, "Все");
        getList("Все");
        all_panel.setBackground(clicked);   
    }//GEN-LAST:event_all_panelMouseClicked

    private void catTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catTableMouseClicked
        // TODO add your handling code here:
        System.out.println(catTable.getSelectedRow());
        TableModel tModel = (TableModel) catTable.getModel();
        SingleItemFrame fr;
        try {
            fr = new SingleItemFrame(tModel.getObj(catTable.getSelectedRow()), this);
            fr.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
            fr.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }//GEN-LAST:event_catTableMouseClicked

    private void filter_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filter_panelMouseClicked
        // TODO add your handling code here:
        skipSelection(6, "Фильтр");
        cbType.setVisible(true);
        cbSugar.setVisible(true);
        cbGrape.setVisible(true);
        cbCountry.setVisible(true);
        searchIcon.setVisible(true);
        FilterObject filterObj = new FilterObject();
        wineList.clear();
        TableModel tModel = new TableModel(wineList.size(), 6, wineList);
        catTable.setModel(tModel);
        try {
            filterObj = db.getFilter();
        } catch (SQLException ex) {
            Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        filter_panel.setBackground(clicked);
        
        for(int i = 0; i < filterObj.getTypeList().size(); i++) {
            cbType.addItem(filterObj.getTypeList().get(i));
        }
        
        for(int i = 0; i < filterObj.getSugarFilter().size(); i++) {
            cbSugar.addItem(filterObj.getSugarFilter().get(i));
        }
        
        for(int i = 0; i < filterObj.getGrapeList().size(); i++) {
            cbGrape.addItem(filterObj.getGrapeList().get(i));
        }
         
        for(int i = 0; i < filterObj.getCountryList().size(); i++) {
            cbCountry.addItem(filterObj.getCountryList().get(i));
        }        
    }//GEN-LAST:event_filter_panelMouseClicked

    private void shamp_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shamp_panelMouseClicked
        // TODO add your handling code here:
        skipSelection(4, "Игристое вино");
        getList("Игристое");
        shamp_panel.setBackground(clicked);
    }//GEN-LAST:event_shamp_panelMouseClicked

    private void searchIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchIconMouseClicked
        // TODO add your handling code here:
        String type = (String) cbType.getSelectedItem();
        String sugar = (String) cbSugar.getSelectedItem();
        String grape = (String) cbGrape.getSelectedItem();
        String country = (String) cbCountry.getSelectedItem();
        wineList.clear();
        if (db.dbConnect()) {
            try {
                wineList = db.getFilterResult(type, sugar, grape, country);
            } catch (SQLException ex) {
                Logger.getLogger(HomeFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        TableModel tModel = new TableModel(wineList.size(), 6, wineList);
        catTable.setModel(tModel);
    }//GEN-LAST:event_searchIconMouseClicked

    private void addDbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDbMouseClicked
        // TODO add your handling code here:
        AddElemFrame frame = new AddElemFrame();
        frame.setVisible(true);
        frame.setDefaultCloseOperation(HIDE_ON_CLOSE);
        
    }//GEN-LAST:event_addDbMouseClicked

    private void shopingCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopingCartMouseClicked
        // TODO add your handling code here:
        skipSelection(6, "Корзина");
        TableModel tModel = new TableModel(shoppingCart.size(), 6, shoppingCart);
        catTable.setModel(tModel);  
        clearCart.setVisible(true);
    }//GEN-LAST:event_shopingCartMouseClicked

    private void clearCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearCartMouseClicked
        // TODO add your handling code here:
        shoppingCart.clear();
        cartCount.setText(" ");
        TableModel tModel = new TableModel(shoppingCart.size(), 6, shoppingCart);
        catTable.setModel(tModel);  
    }//GEN-LAST:event_clearCartMouseClicked

    private void skipSelection(int itemNum, String name) {
        red_panel.setBackground(stock);
        white_panel.setBackground(stock);
        clearCart.setVisible(false);
        rose_panel.setBackground(stock);
        all_panel.setBackground(stock);
        shamp_panel.setBackground(stock);
        filter_panel.setBackground(stock);
        cbType.setVisible(false);
        cbSugar.setVisible(false);
        cbGrape.setVisible(false);
        cbCountry.setVisible(false);
        searchIcon.setVisible(false);
        menuItem = itemNum;
        head_title.setText(name);
        if (itemNum == 0) {
            catTable.setVisible(false);
            jScrollPane1.setVisible(false);
        } else {
            jScrollPane1.setVisible(true);
            catTable.setVisible(true);
        }
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HomeFrame().setVisible(true);
        });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addDb;
    private javax.swing.JPanel all_panel;
    private javax.swing.JPanel basic;
    public javax.swing.JLabel cartCount;
    private static javax.swing.JTable catTable;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JComboBox<String> cbGrape;
    private javax.swing.JComboBox<String> cbSugar;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel clearCart;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel filter_panel;
    private javax.swing.JLabel head;
    private javax.swing.JLabel head_title;
    private javax.swing.JPanel headpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel red_panel;
    private javax.swing.JPanel rose_panel;
    private javax.swing.JLabel searchIcon;
    private javax.swing.JPanel shamp_panel;
    private javax.swing.JLabel shopingCart;
    private javax.swing.JPanel sidemenu;
    private javax.swing.JPanel tablepanel;
    private javax.swing.JPanel white_panel;
    // End of variables declaration//GEN-END:variables

}
